### ISSUE TITLE
Wie finde ich die Länge eines Strings heraus?

### ISSUE THREAD

**Issue by mbrain** [zarat/zvm#2]
Ich lese eine Zeile mit read und speichere sie auf 100. Dann lade ich den String auf den Stack und speichere den Stackindex auf ax.

    push 100
    gets
    si ax
    ldr ax
    push 111
    puts
    ldr ax
    print

Beim ersten Mal bekomme ich immer 1 zuviel, danach funktioniert es genau wie es sollte. Ist das ein Bug oder mach ich etwas falsch?

**Comment by zarat** [comment]
Also ich kann eigentlich keinen Fehler erkennen. Du könntest versuchen, den Stackindex vorher zu speichern, vielleicht war noch etwas oben.

    si bx ; alter stackpointer
    push 100
    gets
    si ax ; neuer stackpointer
    sub ax bx ; alt - neu = aktuell
    ldr ax
    push 111
    puts
    ldr ax 
    print
    jmp main
